// defines default character attribute object
export let Character = {
  profBonus: 3,
  items: "",
  name: "",
  race: "",
  campaign: "",
  alignment: "True Neutral",
  background: "",
  initiative: 2,
  currentHitPoints: 0,
  hitPoints: 0,
  speed: 0,
  armorClass: 0,
  goldCount: 0,
  exp: 0,
  mainClass: { charClass: "", level: 1 },
  subClass: { charClass: "", level: 1 },
  STR: 10,
  DEX: 10,
  CON: 10,
  INT: 10,
  WIS: 10,
  CHA: 10,
};
