// defines default character attribute object
export let Character = {
  profBonus: 3,
  items: [],
  name: "",
  race: "",
  campaign: "",
  alignment: "True Neutral",
  background: "",
  initiative: 2,
  currentHitPoints: 0,
  hitPoints: 0,
  speed: 0,
  armorClass: 0,
  goldCount: 0,
  exp: 0,
  mainClass: { charClass: "", level: 1 },
  subClass: { charClass: "", level: 1 },
  STR: { baseMod: 10, abilityScore: 10, mod: 0 },
  DEX: { baseMod: 10, abilityScore: 10, mod: 0 },
  CON: { baseMod: 10, abilityScore: 10, mod: 0 },
  INT: { baseMod: 10, abilityScore: 10, mod: 0 },
  WIS: { baseMod: 10, abilityScore: 10, mod: 0 },
  CHA: { baseMod: 10, abilityScore: 10, mod: 0 },
};
